### ISSUE TITLE
Shift + Tab incorrectly moves middle item to next item

### ISSUE THREAD

**Issue by evanjmg** [editor-js/nested-list#17]
**Reproducible steps**

3. List
   3.1 sub item
   3.2 <- untab here
   3.3.
4. List 3.2 moves here
5. 4 moved

**Expected Result**

3. parent item
    3.1 sub item
4. <- result of untabing
   4.1.sub item 3
5.  item

**Comment by talyguryn** [comment]
if you want to untab the element then it should not affect other elements in the list. these elements places on the same level so I think that you don't need to place the following items as childs. 

we had think about this behaviour too much and this is the best solution for the moment.
