### ISSUE TITLE
How to store description for each list item 

### ISSUE THREAD

**Issue by abdulrahman1997x** [editor-js/nested-list#18]
hey everyone so i am trying to do something like this

1. item 1
   description 
   1.1 nested item 
        description for the nested Item 
2- description 

it would be like a content or description for each item

**Comment by talyguryn** [comment]
￼￼why you can not use item's content as a description for sublist?

**Comment by abdulrahman1997x** [comment]
> ￼￼why you can not use item's content as a description for sublist?

because each item in my nested list has a title and description.

**Comment by talyguryn** [comment]
it is not an usual usage of lists. so if you need this feature, please fork this repo and upgrade it to your own purposes
