### ISSUE TITLE
I can't load plugin (Uncaught Error: Module parse failed: Unexpected token )

### ISSUE THREAD

**Issue by etokas** [editor-js/nested-list#47]
Hello guys

I come with one issue, I installed this plugin, It's working well until today
I don't know why

If someone can help me

Thanx

My error bellow

![image](https://user-images.githubusercontent.com/12876283/209710772-f2ea51f8-4280-4204-9f36-d9669e64b508.png)

EDIT:
I fork @editor-js/nested-list 

when I build with `yarn build:dev` and copy content of `nested-list/dist/nested-list.js` in my project here `node_modules/@editorjs/nested-list/dist/nested-list.js`
IT'S WORK

but when i build with `yarn build` and copy build production in `node_modules/@editorjs/nested-list/dist/nested-list.js`
IT'S STILL DOES'NT WORKS

Need help :cry: 

EDIT AGAIN 

After many hour to debug 
this bug occur here 

`const getPastedItems = (parent) => {
      // get first level li elements.
      const children = Array.from(parent.querySelectorAll(`:scope > li`));

      return children.map((child) => {
        // get subitems if they exist.
        const subItemsWrapper = child.querySelector(`:scope > ${tagToSearch}`);
        // get subitems.
        const subItems = subItemsWrapper ? getPastedItems(subItemsWrapper) : [];
        // get text content of the li element.
        const content = child?.firstChild?.textContent || ''; // bug here with '?' 

        return {
          content,
          items: subItems,
        };
      });
    };`

I don't know why 

yarn: 1.22.19
editorjs: 2.26.4
nested-list: 1.2.0
react: 17

**Comment by etokas** [comment]
I corrected this by changing the version to 1.1.0
it works now
the bug is introduced by this MR https://github.com/editor-js/nested-list/pull/45

**Comment by simonfan** [comment]
Same issue here
