### ISSUE TITLE
Duplicate input issue in NestedList plugin when using Japanese input

### ISSUE THREAD

**Issue by kenshintatsumi** [editor-js/nested-list#56]
Hello,

I've been experiencing an issue with the NestedList plugin in EditorJS on specific browsers (Google Chrome and Brave). This issue seems to occur only when using Japanese input.

**Describe the bug:**

When typing in Japanese in a NestedList block and pressing Enter, the previously inputted text gets duplicated to the new line.

**Steps to reproduce:**

Open EditorJS with NestedList plugin on Google Chrome or Brave browser.
Switch to Japanese input.
Type some text in a NestedList block.
Press Enter to create a new line.
The previously inputted text is duplicated in the new line.

**Expected behavior:**

When pressing Enter, a new line should be created without duplicating the previous input.

**Environment:**

OS: MacOS Ventura 13.1
Browser: Google Chrome and Brave
Editor.js version:2.27
NestedList version: 1.3.0

**Comment by astrocket** [comment]
@kenshin-tatsumi-dotd https://github.com/editor-js/nested-list/pull/62 will fix your issue
